spring:
  profiles:
    active: home
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  application:
    name: tax-batch

management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always

tax:
  readTimeout: 3000
